@HotelListingApi_HostAddress = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTEzY2Y0MC00Y2FiLTQ2NzYtYjg4NC0yOGMzODRhYjZkN2QiLCJlbWFpbCI6ImhvdGVsYWRtaW4yQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJjZTUxOGEwMy0yZTIzLTQ3NDUtODIzOC00ZjJjNzE5ODQzMTgiLCJuYW1lIjoiSG90ZWwgQWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJIb3RlbCBBZG1pbiIsImV4cCI6MTc2NDQ0MDg2MCwiaXNzIjoiSG90ZWxMaXN0aW5nQXBpIiwiYXVkIjoiSG90ZWxMaXN0aW5nQVBJQ2xpZW50In0.V8Q-9-6WEMcoWdP5LSWZ5KblXmyoZDzxTonfAmDhL84
GET {{HotelListingApi_HostAddress}}/api/hotels
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{HotelListingApi_HostAddress}}/api/hotels
Content-Type: application/json

{
    "name": "Hotel Kosova",
    "address": "42 Sunset Boulevard, Los Pristina",
    "rating": 4.5,
    "CountryId": 2
}

###
PUT {{HotelListingApi_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
    "Id": 5,
    "Name": "Hotel Adriatic",
    "Address": "42 Sunset Boulevard, Los Pristina",
    "Rating": 4.7,
    "CountryId": 2
}

###

DELETE {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###
@id=5
GET {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###

// COUNTRIES CONTROLLER TESTS

GET {{HotelListingApi_HostAddress}}/api/countries
Accept: application/json

###

POST {{HotelListingApi_HostAddress}}/api/countries
Content-Type: application/json

{
    "name": "Spain",
    "shortName": "ES"
}

###

PUT {{HotelListingApi_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
    "id": 2,
    "name": "Kosovo",
    "shortName": "XK"
}

###

DELETE {{HotelListingApi_HostAddress}}/api/countries/{{id}}
###

@id=2
GET {{HotelListingApi_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

###

// USERS CONTROLLER TESTS

POST {{HotelListingApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "email": "hoteladmin2@localhost.com",
    "password": "P@ssword1"
}

###

POST {{HotelListingApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
     "email": "hoteladmin2@localhost.com",
    "password": "P@ssword1",
    "firstName": "Hotel",
    "lastName": "Admin",
    "role": "Hotel Admin",
    "associatedHotelId": 5

}

###



